### ISSUE TITLE
[버그리포트] 로그아웃 될 경우 알람토큰 삭제

### ISSUE THREAD

**Issue by nawhes** [boostcampwm-2021/web30-boostock#189]
로그아웃 될 경우 알람토큰을 삭제해야 할 것 같습니다.
현재는 만료시간 없이 지속되는 쿠키네요

추가로 쿠키는 snake_case를 주로 사용하는 것 같습니다.

**Comment by rnjsrntkd95** [comment]
일별 종목 정보 렌더링, 로그아웃 로직 추가 구현 #186

해당 PR에 로그아웃 시 알람토큰을 제거하고 소켓에게 알리는 로직을 구현해두었습니다.
현재 배포 사이트에서도 로그아웃 시 알람토큰이 정상적으로 제거되네요. 추가적으로 버그 발생하면 말씀해주세요~감사합니다
