### ISSUE TITLE
[호가 컴포넌트] - 가격 및 해당 가격의 매수·매도 요청량 리스트 출력

### ISSUE THREAD

**Issue by jaehyeon48** [boostcampwm-2021/web30-boostock#3]
가격 및 해당 가격의 매수·매도 요청량 리스트 출력

(예시):
![image](https://user-images.githubusercontent.com/50892653/139634349-9528acae-70e1-4994-8e83-6823d276b1c0.png)

**Comment by SYN0P** [comment]
#106 에서 반영
